Create schema.sql
freeridersochi/shop_php pull request #1
Opened 2019-07-29 13:02 UTC by freeridersochi

Создали структуру данных

2019-07-29 13:05 UTC, zeckson requested changes
Добавил комментариев

2019-07-29 13:05 UTC, zeckson commented on data/scheme.sql
> +insert into marks (name) values('hot'),('sale'),('new');
Давай сделаем здесь как и везде в верхнем регистре и отформатируем

2019-07-30 09:56 UTC, zeckson requested changes

2019-07-30 09:56 UTC, zeckson commented on data/scheme.sql
> +VALUES (0 , '../img/snowboards/1_1.jpg',
так просто не получится, нужно прочитать данные из файла при помощи функции
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_load-file

2019-07-30 09:56 UTC, zeckson commented on data/scheme.sql
> +
давай уберем этот пробел

2019-07-30 09:56 UTC, zeckson commented on data/scheme.sql
> +    mark(),
информацию про `FOREIGN_KEY` скину позже немного

2019-07-31 05:58 UTC, zeckson requested changes

2019-07-31 05:58 UTC, zeckson commented on data/scheme.sql
> +    photo(),
здесь надо проставить внешние ключи. Вот здесь можно ознакомиться как они устроены:
https://webformyself.com/sql-vneshnij-klyuch/
https://metanit.com/sql/mysql/2.5.php
https://andreyex.ru/bazy-dannyx/uchebnoe-posobie-po-sql/sql-foreign-key-vneshnij-klyuch/
Если будут вопросы, задавай.

2019-07-31 06:00 UTC, zeckson commented
Свяжи таблицы, как написано в статьях.
Добавь тестовые данные в таблицу `products`.

2019-07-31 13:18 UTC, freeridersochi commented on data/scheme.sql
> +    photo(),
Да. Возник. 
Из таблицы marks например мне нужно забрать значение id (mark INT references marks (id) ) этого достаточно или мне нужно указать конкретное id  и его значение пусть это будет 2 (new)  чтобы sql  подставил его в таблицу products используя имя марки под этим id?

2019-07-31 13:26 UTC, zeckson commented on data/scheme.sql
> +    photo(),
Во-первых, ты всегда можешь попробовать. База данных тебе не даст выполнить противоречивое действие.
Во-вторых, у тебя должно получится что-то вроде:
```
  mark_id INT UNSIGNED NOT NULL,  
  FOREIGN KEY (mark_id) REFERENCES marks (id) ON DELETE RESTRICT,
```

2019-07-31 16:35 UTC, zeckson approved these changes
Отлично!

2019-07-31 16:35 UTC, merged