Create templates
freeridersochi/shop_php pull request #2
Opened 2019-08-01 13:51 UTC by freeridersochi

Перенести product.php в корень, сделать его через шаблоны как home.php. FIx home php. MOve all htmtl pages to php.

2019-08-03 15:36 UTC, zeckson requested changes
Поправь, пожалуйста комментарии, которые я оставил

2019-08-03 15:36 UTC, zeckson commented on pages/personal_area.php
> +$cat_data = [
Эти данные нужны для логина?

2019-08-03 15:36 UTC, zeckson commented on pages/login_page.php
> +$login_data = [
Эти данные не используются в шаблоне, давай их удалим

2019-08-03 15:36 UTC, zeckson commented on pages/product.php
> +    require_once '../src/include/database.php';
Поправь отступы, пожалуйста в этом файле

2019-08-03 15:36 UTC, zeckson commented on pages/shoping_cart.php
> +$basket_data = [
В шаблоне не используются эти данные, давай уберём

2019-08-04 13:43 UTC, freeridersochi commented on pages/personal_area.php
> +$cat_data = [
Эта часть кода подключает функцию шаблонизации. Без нее все ломается.

2019-08-04 13:58 UTC, freeridersochi commented on pages/product.php
> +    require_once '../src/include/database.php';
причесал его.

2019-08-04 13:59 UTC, freeridersochi commented on pages/personal_area.php
> +$cat_data = [
удалил данные из массива, страница на месте, разобрался.

2019-08-04 13:59 UTC, freeridersochi commented on pages/login_page.php
> +$login_data = [
Удалил

2019-08-04 14:00 UTC, freeridersochi commented on pages/shoping_cart.php
> +$basket_data = [
Здесь тоже. Сейчас сделаю коммит со всеми изменениями.

2019-08-05 13:04 UTC, zeckson requested changes

2019-08-05 13:04 UTC, zeckson commented on pages/login_page.php
> +$login_page = include_template('../src/templates/login.php', $login_data );
Если данных, нет, то их можно вообще не передавать и выкинуть. Т.е.
```suggestion
$login_page = include_template('../src/templates/login.php');
```

2019-08-05 13:04 UTC, zeckson commented on pages/personal_area.php
> +$cat_page = include_template('../src/templates/pers_area.php', $cat_data );
```suggestion
$cat_page = include_template('../src/templates/pers_area.php' );
```

2019-08-05 13:04 UTC, zeckson commented on pages/personal_area.php
> +$cat_data = [];
```suggestion
```

2019-08-05 13:04 UTC, zeckson commented on pages/login_page.php
> +$login_data = [];
```suggestion
```

2019-08-05 13:04 UTC, zeckson commented on pages/product.php
> +    require_once '../src/include/database.php';
давай уберём все эти отступы? Как в других файлах?
Зачем тебе эти отступы тут.

2019-08-05 13:04 UTC, zeckson commented on pages/registration_page.php
> +$registration_page = include_template('../src/templates/registration.php', $registration_data );
Давай выкинем неиспользуемый массив, как я показал выше.
Чем меньше у нас ненужных переменных, тем понятнее.

2019-08-05 13:04 UTC, zeckson commented on pages/shoping_cart.php
> +$basket_data = [];
Давай выкинем неиспользуемый массив, как я показал выше.
Чем меньше у нас ненужных переменных, тем понятнее.

2019-08-06 14:32 UTC, zeckson requested changes
Add more comments

2019-08-06 14:32 UTC, zeckson commented on pages/shoping_cart.php
> +$include_result = include_template('../src/templates/layout.php', [
Use `render_page` here

2019-08-06 14:32 UTC, zeckson commented on pages/shoping_cart.php
> +require_once '../src/include/database.php';
Remove it
```suggestion
```

2019-08-06 14:32 UTC, zeckson commented on pages/registration_page.php
> +$include_result = include_template('../src/templates/layout.php', [
Use `render_page` here

2019-08-06 14:32 UTC, zeckson commented on pages/personal_area.php
> +$include_result = include_template('../src/templates/layout.php', [
Use `render_page`

2019-08-06 14:32 UTC, zeckson commented on pages/personal_area.php
> +require_once '../src/include/database.php';
Remove it
```suggestion
```

2019-08-06 14:32 UTC, zeckson commented on pages/registration_page.php
> +require_once '../src/include/database.php';
Remove it
```suggestion
```

2019-08-07 14:50 UTC, freeridersochi commented on pages/login_page.php
> +$login_page = include_template('../src/templates/login.php', $login_data );
Исправлено

2019-08-07 14:50 UTC, freeridersochi commented on pages/personal_area.php
> +$cat_page = include_template('../src/templates/pers_area.php', $cat_data );
+

2019-08-07 14:50 UTC, freeridersochi commented on pages/personal_area.php
> +$cat_data = [];
+

2019-08-07 14:51 UTC, freeridersochi commented on pages/login_page.php
> +$login_data = [];
Исправлено

2019-08-07 14:55 UTC, freeridersochi commented on pages/registration_page.php
> +require_once '../src/include/database.php';
Done.

2019-08-07 14:56 UTC, freeridersochi commented on pages/personal_area.php
> +require_once '../src/include/database.php';
Done.

2019-08-07 14:59 UTC, freeridersochi commented on pages/personal_area.php
> +$include_result = include_template('../src/templates/layout.php', [
Done.

2019-08-07 15:04 UTC, freeridersochi commented on pages/registration_page.php
> +$include_result = include_template('../src/templates/layout.php', [
done.

2019-08-07 15:07 UTC, freeridersochi commented on pages/shoping_cart.php
> +require_once '../src/include/database.php';
Done.

2019-08-07 15:08 UTC, freeridersochi commented on pages/shoping_cart.php
> +$include_result = include_template('../src/templates/layout.php', [
Done.

2019-08-07 15:09 UTC, freeridersochi commented on pages/shoping_cart.php
> +$basket_data = [];
Done.

2019-08-07 15:10 UTC, freeridersochi commented on pages/registration_page.php
> +$registration_page = include_template('../src/templates/registration.php', $registration_data );
Done.

2019-08-08 11:22 UTC, zeckson approved these changes
Belissimo!

2019-08-08 11:23 UTC, merged